# CMake generated Testfile for 
# Source directory: C:/Users/53065/Documents/Software/opencv/sources/modules/videoio
# Build directory: C:/Users/53065/Documents/Software/opencv/build/x64/MinGW/modules/videoio
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(opencv_test_videoio "C:/Users/53065/Documents/Software/opencv/build/x64/MinGW/bin/opencv_test_videoio.exe" "--gtest_output=xml:opencv_test_videoio.xml")
set_tests_properties(opencv_test_videoio PROPERTIES  LABELS "Main;opencv_videoio;Accuracy" WORKING_DIRECTORY "C:/Users/53065/Documents/Software/opencv/build/x64/MinGW/test-reports/accuracy" _BACKTRACE_TRIPLES "C:/Users/53065/Documents/Software/opencv/sources/cmake/OpenCVUtils.cmake;1640;add_test;C:/Users/53065/Documents/Software/opencv/sources/cmake/OpenCVModule.cmake;1282;ocv_add_test_from_target;C:/Users/53065/Documents/Software/opencv/sources/modules/videoio/CMakeLists.txt;191;ocv_add_accuracy_tests;C:/Users/53065/Documents/Software/opencv/sources/modules/videoio/CMakeLists.txt;0;")
add_test(opencv_perf_videoio "C:/Users/53065/Documents/Software/opencv/build/x64/MinGW/bin/opencv_perf_videoio.exe" "--gtest_output=xml:opencv_perf_videoio.xml")
set_tests_properties(opencv_perf_videoio PROPERTIES  LABELS "Main;opencv_videoio;Performance" WORKING_DIRECTORY "C:/Users/53065/Documents/Software/opencv/build/x64/MinGW/test-reports/performance" _BACKTRACE_TRIPLES "C:/Users/53065/Documents/Software/opencv/sources/cmake/OpenCVUtils.cmake;1640;add_test;C:/Users/53065/Documents/Software/opencv/sources/cmake/OpenCVModule.cmake;1193;ocv_add_test_from_target;C:/Users/53065/Documents/Software/opencv/sources/modules/videoio/CMakeLists.txt;192;ocv_add_perf_tests;C:/Users/53065/Documents/Software/opencv/sources/modules/videoio/CMakeLists.txt;0;")
add_test(opencv_sanity_videoio "C:/Users/53065/Documents/Software/opencv/build/x64/MinGW/bin/opencv_perf_videoio.exe" "--gtest_output=xml:opencv_perf_videoio.xml" "--perf_min_samples=1" "--perf_force_samples=1" "--perf_verify_sanity")
set_tests_properties(opencv_sanity_videoio PROPERTIES  LABELS "Main;opencv_videoio;Sanity" WORKING_DIRECTORY "C:/Users/53065/Documents/Software/opencv/build/x64/MinGW/test-reports/sanity" _BACKTRACE_TRIPLES "C:/Users/53065/Documents/Software/opencv/sources/cmake/OpenCVUtils.cmake;1640;add_test;C:/Users/53065/Documents/Software/opencv/sources/cmake/OpenCVModule.cmake;1194;ocv_add_test_from_target;C:/Users/53065/Documents/Software/opencv/sources/modules/videoio/CMakeLists.txt;192;ocv_add_perf_tests;C:/Users/53065/Documents/Software/opencv/sources/modules/videoio/CMakeLists.txt;0;")
